/* ═══════════════════════════════════════════════════════════
   Master Waiters · Language Engine v1.1
   Shared across all investor hub pages
   Toggle: ES ↔ EN · Persists via localStorage
═══════════════════════════════════════════════════════════ */
(function(){
'use strict';

const T = {
  "hub.header_eyebrow.0": "Pre-Seed Round 2026 · Investor Hub · Confidential",
  "hub.header_sub.0": "A gamification platform connecting brands, restaurants and waiters — the most underutilized sales force in the world.",
  "hub.traction_label.0": "Waiter adoption",
  "hub.traction_label.1": "Category sales uplift",
  "hub.traction_label.2": "Challenge completion",
  "hub.traction_label.3": "Raising · SAFE",
  "hub.traction_label.4": "Early Bird Cap",
  "hub.section_label.0": "Strategic documents",
  "hub.section_label.1": "Interactive tools",
  "hub.card_title.0": "Investor Deck<br>Master Waiters",
  "hub.card_title.1": "Global Expansion<br>Plan · 5 Years",
  "hub.card_title.2": "Global Technology<br>Strategy",
  "hub.card_title.3": "SAAF — Superlikers Autonomous Agents Framework",
  "hub.card_desc.0": "Vision, problem, solution, traction, business model and investment opportunity.",
  "hub.card_desc.1": "From 1 to 1,000,000 restaurants. 2026–2031 roadmap, alliance ecosystem and SAFE model.",
  "hub.card_desc.2": "Scaling architecture: apps, landings, SAAF, LMS, partner model and technical roadmap.",
  "hub.card_desc.3": "The AI engine that makes operating 1,000,000 restaurants with a small team possible. 8-layer architecture, proposing agents, approval engine and machine learning. Master Waiters' technological moat.",
  "hub.card_type.0": "Deck",
  "hub.card_type.1": "Strategy",
  "hub.card_type.2": "Technology",
  "hub.card_type.3": "AI · Moat",
  "hub.tool_title.0": "Super Meseros<br>Training Kit",
  "hub.tool_title.1": "Super Meseros<br>ROI Simulator",
  "hub.tool_title.2": "Super Meseros<br>Price Calculator",
  "hub.tool_desc.0": "Training material for sales teams and commercial staff.",
  "hub.tool_desc.1": "Calculate the expected return for a restaurant or sponsoring brand.",
  "hub.tool_desc.2": "Personalized commercial proposal in real time by business type and size.",
  "hub.tool_badge.0": "Live app",
  "hub.tool_badge.1": "Live app",
  "hub.tool_badge.2": "Live app",
  "hub.quote_text.0": "\"When I started using Super Meseros I never imagined that my daily effort could bring me anything more than my salary and tips. I managed to win a television without spending any of my own money, simply by doing my job well.\"",
  "hub.quote_attr.0": "Fernando Dugand · Waiter, HOT Restaurants · Barranquilla, Colombia · 2026",
  "hub.footer_note.0": "Pre-Seed Round · SAFE · Cap $6M Early Bird<br>Superlikers SAS · iWin SAS · Barranquilla, Colombia<br>Confidential document · April 2026",
  "exp.section_eyebrow.0": "01 · The Problem",
  "exp.section_eyebrow.1": "02 · The Solution",
  "exp.section_eyebrow.2": "03 · Validated Traction",
  "exp.section_eyebrow.3": "04 · Global Expansion Plan",
  "exp.section_eyebrow.4": "05 · The Technological Moat",
  "exp.section_eyebrow.5": "06 · Alliance Ecosystem",
  "exp.section_eyebrow.6": "07 · The Master Waiters Gala",
  "exp.section_eyebrow.7": "08 · The Investment Opportunity",
  "exp.section_eyebrow.8": "09 · Why Now",
  "exp.section_eyebrow.9": "10 · The Founding Team",
  "exp.section_title.0": "50 million waiters.<br>Invisible to brands.",
  "exp.section_title.1": "Master Waiters.",
  "exp.section_title.2": "The pilot numbers<br>speak for themselves.",
  "exp.section_title.3": "1 → 1,000,000<br>in 60 months.",
  "exp.section_title.4": "SAAF: the engine that<br>makes scale possible.",
  "exp.section_title.5": "An ecosystem designed<br>for global expansion.",
  "exp.section_title.6": "The event the industry<br>needs and doesn't have.",
  "exp.section_title.7": "Pre-seed · SAFE · USD $500K.",
  "exp.section_title.8": "The exact moment.",
  "exp.section_title.9": "Built by someone<br>who has done it before.",
  "exp.section_lead.0": "The waiter is the last mile of distribution in the restaurant channel. They talk to the customer, recommend the product, close the sale. Yet no brand knows what happens in that conversation, nor can measure or influence it systematically.",
  "exp.section_lead.1": "A high-performance enterprise gamification platform that turns the waiter's daily work into a strategic game with clear rules, real-time metrics and real rewards — partially funded by the brands that benefit from their performance.",
  "exp.section_lead.2": "Master Waiters operates in Colombia under the brand \"Super Meseros\" since Q1 2026, with HOT Restaurants as the pilot chain and Coca-Cola Colombia as the first sponsoring brand in active conversations.",
  "exp.section_lead.3": "The expansion is not linear. It is a network effect: each brand that joins attracts restaurants, each restaurant that joins attracts more brands, and the platform becomes more valuable for everyone as it grows.",
  "exp.section_lead.4": "The bottleneck of any enterprise gamification platform is the human team that designs and manages strategies for each client. SAAF (Superlikers Autonomous Agents Framework) eliminates that bottleneck.",
  "exp.section_lead.5": "Master Waiters does not grow alone. The expansion strategy relies on an alliance ecosystem structured in seven categories, each with a specific role and a clear participation model — from technology integration to strategic co-creation.",
  "exp.section_lead.6": "The restaurant industry has no world-class event celebrating those who make the experience possible: the waiters. The Master Waiters Gala fills that void and becomes the platform's most powerful visibility anchor.",
  "exp.section_lead.7": "A seed capital round designed to validate the complete autonomous SAAF flow and prove to Coca-Cola Colombia that we can operate 5,000 restaurants without operational friction — the milestone that unlocks the Series A round.",
  "exp.section_lead.8": "Three conditions that have never coincided simultaneously — making the next 18 months the critical window to establish the global gamification standard for restaurants.",
  "exp.card_title.0": "The restaurant's problem",
  "exp.card_title.1": "The brands' problem",
  "exp.card_title.2": "The waiter's problem",
  "exp.card_title.3": "The scale problem",
  "exp.card_title.4": "For restaurants",
  "exp.card_title.5": "For sponsoring brands",
  "exp.card_title.6": "For waiters",
  "exp.card_title.7": "The business model",
  "exp.card_title.8": "The problem SAAF solves",
  "exp.card_title.9": "What SAAF does",
  "exp.card_title.10": "01 · Product-Led Growth",
  "exp.card_title.11": "02 · Brand channel",
  "exp.card_title.12": "03 · Authorized partner network",
  "exp.card_title.13": "First edition — 2026 (Colombia)",
  "exp.card_title.14": "International edition — 2027",
  "exp.card_title.15": "Why the Gala matters strategically",
  "exp.card_title.16": "Co-architects of the Gala",
  "exp.card_title.17": "Coca-Cola Colombia has a mandate",
  "exp.card_title.18": "AI now makes SAAF possible",
  "exp.card_title.19": "The category has no global competitor",
  "exp.card_title.20": "15 years of built infrastructure",
  "exp.card_desc.0": "No tool exists to simply measure team performance, motivate them based on real results or align their actions with business goals. Incentive programs are manual, sporadic and data-free.",
  "exp.card_desc.1": "Brands invest millions in trade marketing at points of sale, but have no visibility on how effective the waiter's recommendation is. No direct channel, no measurement, no clear ROI from restaurant spending.",
  "exp.card_desc.2": "The waiter has no tools for professional development, receives no recognition proportional to their sales impact, and has no visibility beyond the tips they receive.",
  "exp.card_desc.3": "Existing corporate incentive solutions are not designed for independent restaurants or for operating in thousands of establishments simultaneously. They require human staff per client, making linear growth impossible.",
  "exp.card_desc.4": "Monthly SaaS subscription. Challenge system that motivates the team based on real sales metrics. Performance dashboard by waiter, shift and location. Full onboarding in 48 hours.",
  "exp.card_desc.5": "Direct trade marketing channel to the waiter. Access to thousands of restaurants via a single integration. Category sales impact dashboard. Sponsored challenges with their logo and commercial goals.",
  "exp.card_desc.6": "Free mobile app. Super Coins earned by completing challenges, redeemable for real prizes (electronics, experiences, gift cards). Peer ranking and recognition. Product and service certifications.",
  "exp.card_desc.7": "Two complementary revenue streams: <strong>SaaS (~45%)</strong> — monthly fee per waiter to restaurants and brands. <strong>Super Coins (~55%)</strong> — incentive currency purchased by restaurants and brands, with 10% net breakage. Brands subsidize up to 50% of the restaurant's cost.",
  "exp.card_desc.8": "Without AI: each new client requires proportional time from the Engagement Manager team. With 23 restaurants, manageable. With 5,000 or 28,000, impossible without proportional team growth — destroying the business model.",
  "exp.card_desc.9": "An autonomous agent system that analyzes each restaurant's POS in real time, proposes a monthly batch of calibrated challenges for that restaurant and brand, manages approvals, and publishes — always with a human in the final loop.",
  "exp.card_desc.10": "30-day free trial without credit card. Complete self-service funnel: demo, quote, payment, onboarding — no sales team needed for individual restaurants. The commercial calculator is already built and deployed.",
  "exp.card_desc.11": "Each sponsoring brand that activates challenges in restaurants automatically becomes a promoter of Master Waiters among their distribution clients. The brand's trade marketing budget pays for platform expansion.",
  "exp.card_desc.12": "500 certified regional partners, each with a target portfolio of 2,000 restaurants in their territory. 30% MRR revenue share. Equity path via SAFE for the most strategic ones.",
  "exp.card_desc.13": "Awards ceremony for the best waiters by category, region and specialty. In-app nominations. Presence of sponsoring brands, restaurant chains and industry leaders. Global livestream. Co-produced with the Association.",
  "exp.card_desc.14": "Expansion throughout Latin America, with rotating venue. Co-organized with Global Advisory Board members. The most important restaurant service event in Latin America — created by Master Waiters.",
  "exp.card_desc.15": "The Gala generates: free media coverage, brand ambassadors (winning waiters), months of social content, institutional credibility with brands and associations, and the narrative that Master Waiters is not just software — it's a movement elevating the waiter profession.",
  "exp.card_desc.16": "Global Advisory Board members are co-hosts and content curators of the Gala. Their presence and name immediately legitimizes it in the markets where they operate. It is one of the most visible and high-impact forms of their participation in the project.",
  "exp.card_desc.17": "Coca-Cola Colombia's interest in scaling Master Waiters to 5,000 restaurants is not just another lead — it's the proof of concept that the Series A round needs. If we validate it in year 1, the conditions of the next round will be significantly better for all pre-seed participants.",
  "exp.card_desc.18": "The autonomous agent technology that makes SAAF possible did not exist three years ago with sufficient maturity. Claude Sonnet from Anthropic has the level of reasoning and comprehension of Latin American Spanish needed to propose culturally correct gamification challenges. This is the right year.",
  "exp.card_desc.19": "No platform exists globally that connects brands, restaurants and waiters through gamification with the integration depth that Master Waiters has. The window to establish the standard is now — before major tech platforms look at this category.",
  "exp.card_desc.20": "Superlikers (2010) has spent 15 years building the technology platform, processes and relationships with enterprise clients such as AB InBev, Pernod Ricard, Essity and OXXO. Master Waiters is not a startup from scratch — it is the restaurant verticalization of a proven enterprise platform.",
  "exp.callout.0": "<strong>The cross-subsidy is the differentiator.</strong> The more brands activate challenges in a restaurant, the lower the subscription cost for that restaurant — up to 50% discount with 5 active brands. This turns brands into the restaurant acquisition engine, inverting the traditional sales model.",
  "exp.callout.1": "<strong>Active pipeline:</strong> Coca-Cola Colombia is in advanced conversations to activate Master Waiters in 5,000 restaurants in its distribution network. This single client would represent a jump from 23 to more than 5,000 locations — without growing the operations team, thanks to SAAF.",
  "exp.callout.2": "<strong>The multiplier that takes us from 100K to 1M:</strong> In year 5, global brands (Coca-Cola, Heineken, Diageo, Nestlé) turn their distribution network into the Master Waiters sales channel. Growth stops depending on the team and starts depending on brand trade marketing budgets, which are already allocated.",
  "exp.callout.3": "<strong>The three hardest ingredients are already built:</strong> the connection to HOT's POS in real time is in production, the challenge configuration endpoints exist, and the gamification engine runs with real waiters. SAAF is built <em>on top of</em> that infrastructure — it doesn't replace it.",
  "exp.callout.4": "<strong>The alignment mechanism:</strong> Each restaurant an advisor connects, each chain they introduce, each brand they facilitate — becomes an additional fraction of their stake in Master Waiters. The more the platform grows thanks to the advisor, the larger their share of the platform.",
  "exp.partner_tier_title.0": "Global Advisory Board — Strategic Industry Experts",
  "exp.partner_tier_title.1": "Regional Growth Partners — Territory-Authorized Distribution",
  "exp.partner_tier_title.2": "Technology Partners — POS Providers and Management Systems",
  "exp.partner_tier_title.3": "Sponsoring Brands — B2B Clients and Expansion Engine",
  "exp.partner_tier_title.4": "Restaurant Associations — Market Access and Institutional Credibility",
  "exp.partner_tier_title.5": "Influencers and Content Creators — Restaurant Owner and Waiter Communities",
  "exp.partner_tier_title.6": "Hospitality Schools — Waiter Acquisition Channel and Credibility",
  "exp.partner_tier_desc.0": "A curated group of 10 to 15 global experts with deep knowledge of the restaurant industry, active networks in expansion markets, and vision to co-build the international standard. Their contribution is in-kind — knowledge, methodology, introductions and presence — valued and applied as participation in the round's SAFE. It is not an affiliate program: it is co-authorship of the project.",
  "exp.partner_tier_desc.1": "Companies or individuals with local presence, restaurant networks and sales capacity in a specific market. They receive territorial exclusivity with activation minimums, access to the certification program, demo sandbox, and AI-generated co-branded collateral. 30% MRR revenue share from their portfolio, with equity participation option in future stages.",
  "exp.partner_tier_desc.2": "POS integration is the technical entry point for Master Waiters in any restaurant. Each POS provider that integrates with the platform turns their installed base into an instant distribution channel. The goal is 50+ certified connectors by year 5.",
  "exp.partner_tier_desc.3": "Consumer brands that distribute through restaurants are simultaneously Master Waiters clients and their primary expansion vector. When a brand activates its gamification strategy in 5,000 restaurants, those restaurants become platform users — paid in part by the brand itself.",
  "exp.partner_tier_desc.4": "Restaurant industry associations grant massive access to their member bases, institutional credibility in each market and direct communication channels to owners and operators. The presentation of Master Waiters at ACODRES's La Receta Dorada (Cartagena, April 2026) is the first event of this kind.",
  "exp.partner_tier_desc.5": "Digital creators with audiences of restaurant owners, chefs and waiters on TikTok, Instagram and YouTube. Their authenticity and organic reach cannot be bought with advertising. The program includes content collaborations, early feature access and participation in the Gala.",
  "exp.partner_tier_desc.6": "Hospitality schools train the waiters of the future. Integrating Master Waiters as a learning tracking tool in training programs positions the platform as the industry standard and creates a base of young users before they arrive at their first job.",
  "exp.timeline_markets.0": "Colombia · Mexico · Peru",
  "exp.timeline_markets.1": "USA Hispanic · Brazil · Chile · Spain · Argentina",
  "exp.timeline_markets.2": "USA · UK · Europe · Middle East · Asia Pacific",
  "exp.timeline_label.0": "Year 1",
  "exp.timeline_label.1": "Year 3",
  "exp.timeline_label.2": "Year 5",
  "exp.rc_markets.0": "Colombia, Mexico, Peru",
  "exp.rc_markets.1": "USA Hispanic, Brazil, Chile, Spain",
  "exp.rc_markets.2": "Argentina, UK, France, Italy",
  "exp.rc_markets.3": "MEA, Southeast Asia, Eastern Europe",
  "exp.rc_markets.4": "Asia Pacific, Oceania, global consolidation",
  "exp.quote_text.0": "\"Fernando Dugand, a waiter at HOT Restaurants in Barranquilla, won a television simply by doing his job well. He didn't need a union or to ask for a raise. Just consistency, measurement and the right system.\"",
  "exp.quote_attr.0": "Real story from the pilot · Super Meseros · HOT Restaurants · Barranquilla, 2026",
  "tech.hero_eyebrow.0": "Master Waiters · Superlikers · Global Technology Strategy · April 2026 · Confidential",
  "tech.hero_title.0": "From 1 to 1,000,000 restaurants in 5 years:<br>the complete technology architecture",
  "tech.hero_sub.0": "How a single platform, operated by autonomous agents and distributed by regional partners, can turn Master Waiters into the global gamification standard for waiters — without growing the team proportionally to the number of clients.",
  "tech.kpi_label.0": "Target restaurants",
  "tech.kpi_label.1": "Timeline",
  "tech.kpi_label.2": "Scale engine",
  "tech.kpi_note.0": "~7% of global market of 15M restaurants",
  "tech.kpi_note.1": "Q2 2026 → Q1 2031",
  "tech.kpi_note.2": "Self-service + Regional partner network",
  "tech.callout.0": "<b>Core thesis:</b> The only way to go from 23 locations to 1M restaurants without breaking operationally is for the platform to sell, onboard, configure and execute the gamification strategy <em>by itself</em>. SAAF already solves execution. This strategy solves the rest.",
  "tech.section_title.0": "Mobile apps — Localization engine and persona variants",
  "tech.section_sub.0": "One codebase. Dozens of culturally accurate experiences.",
  "tech.callout.1": "<b>Core principle:</b> No new app is built per language or culture. A <em>variant architecture</em> is built that allows launching in a new market in days, not months.",
  "tech.block_title.0": "Internationalization stack",
  "tech.block_title.1": "Active and planned product variants",
  "tech.as_label.0": "Source",
  "tech.as_title.0": "Master content ES-CO",
  "tech.as_label.1": "Layer 1",
  "tech.as_title.1": "Claude API",
  "tech.as_label.2": "Layer 2",
  "tech.as_title.2": "Local human validator",
  "tech.as_label.3": "Production",
  "tech.as_title.3": "Lokalise → i18next",
  "tech.block_title.2": "What gets adapted per market (beyond language)",
  "tech.section_title.1": "Web pages and landings — Digital acquisition engine by market",
  "tech.section_sub.1": "A headless CMS. Dozens of pages segmented by audience, language and vertical.",
  "tech.block_title.3": "Recommended stack",
  "tech.block_title.4": "Landing page tree by audience",
  "tech.callout.2": "<b>Local SEO as a free acquisition channel:</b> Content generated with Claude API for keywords like \"how to motivate waiters\", \"restaurant gamification\", \"restaurant employee loyalty program\" — localized by country with local market data.",
  "tech.section_title.2": "Social media — Multichannel AI content factory",
  "tech.section_sub.2": "One master piece of content, automatically adapted to each platform and market.",
  "tech.block_title.5": "TikTok / Instagram Reels",
  "tech.block_title.6": "LinkedIn / YouTube",
  "tech.block_title.7": "AI content factory",
  "tech.block_title.8": "User-Generated Content (UGC) strategy",
  "tech.section_title.3": "Marketing and promotion — Acquisition engine without a sales team",
  "tech.section_sub.3": "Product-Led Growth as the core strategy. The product sells itself when the funnel works.",
  "tech.block_title.9": "Acquisition channels by priority",
  "tech.block_title.10": "The Master Waiters viral loop",
  "tech.section_title.4": "Pre-sales, sales and post-sales — 100% self-service funnel",
  "tech.section_sub.4": "No sales team for individual restaurants. Human sales only for large chains and brands.",
  "tech.as_label.4": "Top of funnel",
  "tech.as_title.4": "Interactive demo",
  "tech.as_label.5": "Activation",
  "tech.as_title.5": "30-day trial",
  "tech.as_label.6": "Conversion",
  "tech.as_title.6": "In-app payment",
  "tech.as_label.7": "Retention",
  "tech.as_title.7": "AI Success",
  "tech.as_label.8": "Expansion",
  "tech.as_title.8": "Auto upsell",
  "tech.block_title.11": "AI-assisted pre-sales",
  "tech.block_title.12": "Post-sales / AI Customer Success",
  "tech.callout.3": "<b>The pricing calculator already exists</b> (supermeseros_pricing_calculator.html already built). Integrating it into the web self-service flow is the #1 priority for this axis.",
  "tech.section_title.5": "Onboarding — Time to first value in < 48 hours",
  "tech.section_sub.5": "Two parallel journeys: restaurant admins and waiters. Both gamified from minute 1.",
  "tech.block_title.13": "Administrator / owner journey",
  "tech.block_title.14": "Waiter journey",
  "tech.block_title.15": "Multi-language onboarding infrastructure",
  "tech.section_title.6": "SAAF — Scaling the autonomous gamification engine globally",
  "tech.section_sub.6": "The architecture is already designed. It now needs to be prepared to operate in 10+ languages, 50+ currencies and 1M+ restaurants.",
  "tech.callout.4": "<b>SAAF already solves the core operational scale problem.</b> Without it, each new restaurant would require Engagement Manager time. With it, 1M restaurants are operable by a small team. The priority now is <em>internationalizing</em> SAAF, not redesigning it.",
  "tech.block_title.16": "What SAAF needs for global scale",
  "tech.block_title.17": "POS connector priorities by market",
  "tech.highlight_box.0": "<div class=\"hb-title\">New SAAF axis for global scale: the Partner Agent</div><div style=\"font-size:12px;color:var(--color-text-secondary);\">A new type of agent in the SAAF hierarchy: the <strong>Regional Partner Agent</strong>. It operates across all restaurants in a regional partner's portfolio, identifies benchmarks across markets, and proposes best practices that the partner can distribute to their clients. It turns the partner into a \"gamified superintendent\" of their region.</div>",
  "tech.section_title.7": "Training courses and content — Native gamified LMS + external channel",
  "tech.section_sub.7": "Learning as a competitive advantage. Master Waiters waiters are the best trained in the world.",
  "tech.block_title.18": "In-app LMS (Learning)",
  "tech.block_title.19": "External channel (YouTube)",
  "tech.block_title.20": "AI course infrastructure",
  "tech.block_title.21": "LMS monetization as an additional product",
  "tech.section_title.8": "Expansion model and partner materials",
  "tech.section_sub.8": "The most critical decision in the plan: how to distribute Master Waiters globally without losing product control.",
  "tech.section_label.0": "Comparison of expansion models",
  "tech.dc_title.0": "Traditional franchise",
  "tech.dc_title.1": "Authorized Growth Partner",
  "tech.dc_title.2": "Direct expansion",
  "tech.dc_rec.0": "Recommended",
  "tech.block_title.22": "Partner certification program",
  "tech.block_title.23": "Partner portal (tech stack)",
  "tech.section_title.9": "Other critical digital assets for global scale",
  "tech.section_sub.9": "Ecosystem infrastructure that turns Master Waiters from product to industry standard.",
  "tech.block_title.24": "API Marketplace for integrators",
  "tech.block_title.25": "Annual Master Waiters Gala",
  "tech.block_title.26": "Digital thought leadership",
  "tech.section_title.10": "1M restaurant roadmap — 5 years",
  "tech.section_sub.10": "The path is not linear: speed accelerates each year thanks to network effects.",
  "tech.rc_year.0": "Year 1 · 2026",
  "tech.rc_year.1": "Year 2 · 2027",
  "tech.rc_year.2": "Year 3 · 2028",
  "tech.rc_year.3": "Year 4 · 2029",
  "tech.rc_year.4": "Year 5 · 2031",
  "tech.rc_markets.0": "Colombia, Mexico, Peru",
  "tech.rc_markets.1": "USA Hispanic, Brazil, Chile, Spain",
  "tech.rc_markets.2": "Argentina, UK, France, Italy",
  "tech.rc_markets.3": "MEA, Southeast Asia, Eastern Europe",
  "tech.rc_markets.4": "Asia Pacific, Oceania, global consolidation",
  "tech.callout.5": "<b>The multiplier that takes us from 100K to 1M:</b> In year 5, every new restaurant that joins the ecosystem brings its suppliers with it (brands wanting to activate challenges), who in turn promote Master Waiters to other restaurants. Growth stops being linear and becomes exponential when brands become the sales channel.",
  "saaf.section_eyebrow.0": "01 · The scale problem",
  "saaf.section_eyebrow.1": "02 · The technology solution",
  "saaf.section_eyebrow.2": "03 · Technical architecture",
  "saaf.section_eyebrow.3": "04 · Agent hierarchy",
  "saaf.section_eyebrow.4": "05 · From 1 to 1,000,000",
  "saaf.section_eyebrow.5": "06 · The competitive advantage",
  "saaf.section_eyebrow.6": "07 · Technology stack and costs",
  "saaf.section_eyebrow.7": "08 · The MVP that proves it all",
  "saaf.section_title.0": "Master Waiters' promise has a bottleneck.",
  "saaf.section_title.1": "SAAF doesn't replace people. It multiplies them.",
  "saaf.section_title.2": "8 layers. The three hardest are already built.",
  "saaf.section_title.3": "One agent per level. All propose. The admin always decides.",
  "saaf.section_title.4": "SAAF is the difference between a promise and a credible plan.",
  "saaf.section_title.5": "The moat that cannot be easily copied.",
  "saaf.section_title.6": "Manageable inference costs even at full scale.",
  "saaf.section_title.7": "13 weeks to validate the complete autonomous flow.",
  "saaf.section_lead.0": "The platform connects brands, restaurants and waiters in a high-performance gamification ecosystem. The model works. The pilot proves it. But operating at 5,000 restaurants with the same human model that works at 23 is simply impossible.",
  "saaf.section_lead.1": "Superlikers Autonomous Agents Framework is a layer of autonomous agents sitting on top of the existing platform. It does not modify the gamification engine, waiter apps, or endpoints already running in production. It complements them with proactive intelligence.",
  "saaf.section_lead.2": "The most complex technical infrastructure of SAAF is not built from scratch — it already exists and operates in production. SAAF is built on top of that foundation.",
  "saaf.section_lead.3": "SAAF's multi-agent architecture mirrors the real business hierarchy. There is no single generic agent — there are specific instances that understand the context of each level.",
  "saaf.section_lead.4": "Without SAAF, the path to 1M restaurants would require an army of Engagement Managers. With SAAF, scale is an architectural consequence — not an operational problem.",
  "saaf.section_lead.5": "SAAF is not just an automation system. It is a flywheel that spins faster with each restaurant that joins. Data from 1M restaurants makes the agent exponentially more precise than any competitor starting from scratch.",
  "saaf.section_lead.6": "The technology stack was selected to operate asynchronously from the start — the architecture that works at 23 locations works at 5,000 without structural changes.",
  "saaf.section_lead.7": "The SAAF MVP is not a proof of concept. It is the operational demonstration that allows Superlikers to present to Coca-Cola Colombia the technical argument to commit 5,000 restaurants.",
  "saaf.callout.0": "<strong>Non-negotiable design principle:</strong> SAAF never publishes a challenge without human supervision. There is always at least one human in the flow before a challenge is visible to participants. The Engagement Manager approves the full monthly batch first; the admin always retains the final veto — in every flow, for every ecosystem.",
  "saaf.callout.1": "<strong>Why this matters for investors:</strong> The HOT POS connection in real time is already in production. The challenge configuration endpoints already exist. The gamification engine already runs with real waiters. SAAF is built <em>on top of</em> that infrastructure — not replacing it. The hardest part is done.",
  "saaf.callout.2": "<strong>The investment argument:</strong> The SAAF MVP costs ~$500K to develop and validates whether 1M restaurants are operationally achievable. Without SAAF, the Series A argument doesn't exist. With SAAF validated, the Series A argument is practically unbeatable.",
  "saaf.card_title.0": "Proposing Agent",
  "saaf.card_title.1": "Approval Engine",
  "saaf.card_title.2": "Publishing Agent",
  "saaf.card_title.3": "The agent improves with each cycle",
  "saaf.card_title.4": "The agent improves with scale",
  "saaf.card_title.5": "The POS is already connected",
  "saaf.card_title.6": "Design that respects client autonomy",
  "saaf.card_title.7": "One system, infinite ecosystems",
  "saaf.card_title.8": "Claude Sonnet (Anthropic)",
  "saaf.card_title.9": "AWS · Python / FastAPI",
  "saaf.layer_name.0": "Data sources",
  "saaf.layer_name.1": "Normalized connectors",
  "saaf.layer_name.2": "Proposing agents",
  "saaf.layer_name.3": "Approval engine",
  "saaf.layer_name.4": "Notification channel",
  "saaf.layer_name.5": "Learning engine",
  "saaf.layer_name.6": "Publishing agent",
  "saaf.layer_name.7": "Superlikers platform",
  "saaf.layer_desc.0": "HOT Restaurants POS in real time · OXXO POS · Corporate ERP",
  "saaf.layer_desc.1": "All POS systems deliver the same structure to the agent · interchangeable",
  "saaf.layer_desc.2": "One instance per level: Brand / Chain / Location · proactively proposes without being asked",
  "saaf.layer_desc.3": "Configurable flow per client · Admin always has final veto · AWS Step Functions",
  "saaf.layer_desc.4": "Push · WhatsApp Business (inline approval buttons) · Email",
  "saaf.layer_desc.5": "Real results + EM feedback loop back to the agent · continuous improvement",
  "saaf.layer_desc.6": "Builds the payload · publishes via API · real-time anomaly monitor",
  "saaf.layer_desc.7": "Gamification engine · waiter apps · challenge configuration API endpoints",
  "saaf.quote_text.0": "\"Superlikers' promise was always that more clients shouldn't mean proportionally more people. SAAF is the technical answer to that promise.\"",
  "saaf.quote_attr.0": "— Luis Alberto Del Castillo Cadavid, Founder and CEO, Superlikers",
  "saaf.footer_note.0": "This document is confidential and prepared exclusively for investors and strategic allies of Master Waiters / Superlikers. April 2026.",
  "exp.traction_label.0": "100% waiter adoption in first month",
  "exp.traction_label.1": "Uplift in sponsored category sales",
  "exp.traction_label.2": "Active locations in pilot (HOT Restaurants)",
  "exp.traction_label.3": "0% restaurant churn in active pilot",
  "exp.safe_card.0": "<div class=\"sc-eyebrow\">Early Bird · First USD $250K</div><div class=\"sc-title\">Cap USD $6,000,000</div><div class=\"sc-sub\">Conditions available until early bird quota is filled</div>",
  "exp.safe_card.1": "<div class=\"sc-eyebrow\">Standard · USD $250K – $500K</div><div class=\"sc-title\">Cap USD $8,000,000</div><div class=\"sc-sub\">Conditions after early bird quota is filled</div>",
  "exp.footer_note.0": "",
  "exp.footer_contact.0": "Superlikers SAS / iWin SAS<br/>Barranquilla, Colombia<br/>www.masterwaiters.com",
  "tech.section_label.1": "Self-service funnel for restaurants",
  "tech.section_label.2": "Comparison of expansion models",
  "tech.footer_note.0": "Superlikers · Master Waiters Global Tech Strategy · April 2026 · Confidential",
  "exp.cover_badge.0": "Global Expansion Plan · Partner &amp; Investor Overview · Confidential",
  "exp.cover_eyebrow.0": "Master Waiters · Superlikers · Cartagena, April 2026",
  "exp.cover_meta_label.0": "Instrument",
  "exp.cover_meta_label.1": "Round",
  "exp.cover_meta_label.2": "Founder &amp; CEO",
  "exp.cover_meta_label.3": "Active pilot",
  "exp.cover_meta_val.0": "SAFE · Cap USD $6M (Early Bird)",
  "exp.cover_meta_val.1": "Pre-seed · USD $500,000",
  "exp.cover_meta_val.2": "Luis Alberto Del Castillo · Superlikers (2010)",
  "exp.cover_meta_val.3": "23 restaurants · HOT · Colombia",
  "exp.cover_sub.0": "The world's first platform that connects brands, restaurants and waiters through high-performance gamification — and the autonomous agents that make it possible to operate at global scale without growing the team proportionally.",
  "exp.cover_title.0": "From <em>1</em> to <em>1,000,000</em><br/>restaurants<br/>in 5 years.",
  "exp.cta_eyebrow.0": "Ready to build it together?",
  "exp.cta_label.0": "Email",
  "exp.cta_label.1": "WhatsApp",
  "exp.cta_label.2": "Headquarters",
  "exp.cta_loc_val.0": "Barranquilla, Colombia",
  "exp.cta_sub.0": "The opportunity exists. The technology is ready. The pilot is validated. What remains is to choose well the people who will build this with us.",
  "exp.cta_title.0": "50 million waiters<br/>are waiting for a standard.",
  "exp.founder_bio.0": "In 2010, he founded Superlikers with the vision that gamification could transform business performance. 15 years later, the company has USD $1.7M ARR with clients like AB InBev (Grupo Modelo and Bavaria), Pernod Ricard, Essity and OXXO — all Fortune 500 companies.",
  "exp.founder_company.0": "Superlikers / Master Waiters",
  "exp.founder_m_lbl.0": "Company:",
  "exp.founder_m_lbl.1": "Founded:",
  "exp.founder_m_lbl.2": "Superlikers ARR:",
  "exp.founder_m_lbl.3": "Clients:",
  "exp.founder_m_lbl.4": "Contact:",
  "exp.founder_m_val.0": "iWin SAS (Superlikers)",
  "exp.founder_m_val.1": "2010 · Barranquilla, Colombia",
  "exp.founder_m_val.2": "USD $1.7M",
  "exp.founder_m_val.3": "AB InBev, Pernod Ricard, OXXO, Essity",
  "exp.founder_name.0": "Luis Alberto Del Castillo",
  "exp.founder_title.0": "Founder &amp; CEO",
  "exp.funds_desc.0": "Proposing agents, approval engine, publishing agent",
  "exp.funds_desc.1": "First 3 authorized partners, local adaptations",
  "exp.funds_desc.2": "AWS, additional POS connectors, security",
  "exp.funds_desc.3": "Formal launch, first National Gala",
  "exp.funds_desc.4": "Partner agreements, SAFE, international incorporation",
  "exp.funds_h3.0": "Use of funds",
  "exp.funds_row.0": "SAAF Development (full MVP)",
  "exp.funds_row.1": "Expansion to Mexico + Peru",
  "exp.funds_row.2": "Technical infrastructure",
  "exp.funds_row.3": "Marketing and 2026 Gala",
  "exp.funds_row.4": "Legal and structuring",
  "exp.funds_th.0": "Destination",
  "exp.funds_th.1": "% of round",
  "exp.funds_th.2": "Description",
  "exp.growth_vectors_h3.0": "The three growth vectors",
  "exp.inkind_h3.0": "In-kind participation model — Global Advisory Board",
  "exp.inkind_lead.0": "For Global Advisory Board members, participation in the round does not require cash capital. The contribution is structured, quantified and documented as in-kind investment, accumulating participation in the SAFE through verifiable contributions:",
  "exp.inkind_step.0": "<strong>Strategic advisory:</strong> Working sessions on pricing, expansion model and product decisions. Valued at the expert's consulting rate, documented and applied to the SAFE cumulatively.",
  "exp.inkind_step.1": "<strong>Client introductions:</strong> Each client closed directly through the advisor's network generates a 20% commission on the first year of contract. That commission is not paid in cash — it is automatically credited to their SAFE participation.",
  "exp.inkind_step.2": "<strong>Academy content:</strong> Exclusive educational material contributed to the Master Waiters training platform. Valued by production hours and potential reach.",
  "exp.inkind_step.3": "<strong>Co-authorship of the International Gala:</strong> Participation as co-host and content curator of the event. Valued by brand visibility, contact base contributed, and co-production hours.",
  "exp.market_footnote.0": "* Projection based on average ACV of USD $200/month per restaurant (combined SaaS + Super Monedas revenue). The 1M restaurant target represents ~7% of the global market of 15M establishments.",
  "exp.market_h3.0": "Market projection",
  "exp.market_mk.0": "Colombia, Mexico, Peru",
  "exp.market_mk.1": "+ USA Hispanic, Brazil, Chile, Spain",
  "exp.market_mk.2": "+ Argentina, UK, France, Italy",
  "exp.market_mk.3": "+ MEA, Southeast Asia, Eastern Europe",
  "exp.market_mk.4": "+ Asia Pacific, Oceania, global consolidation",
  "exp.market_th.0": "Year",
  "exp.market_th.1": "Restaurants",
  "exp.market_th.2": "Projected ARR (USD)",
  "exp.market_th.3": "Primary markets",
  "exp.market_year.0": "2026 · Year 1",
  "exp.market_year.1": "2027 · Year 2",
  "exp.market_year.2": "2028 · Year 3",
  "exp.market_year.3": "2029 · Year 4",
  "exp.market_year.4": "2031 · Year 5",
  "exp.saaf_arch_h3.0": "8-layer architecture",
  "exp.saaf_infra_label.0": "Infrastructure",
  "exp.saaf_infra_sub.0": "Lambda + Step Functions + SQS + RDS",
  "exp.saaf_infra_val.0": "AWS · Python/FastAPI",
  "exp.saaf_layer_desc.0": "Real-time POS, corporate ERP, KPIs per ecosystem",
  "exp.saaf_layer_desc.1": "All POS systems deliver the same structure to the agent",
  "exp.saaf_layer_desc.2": "One instance per ecosystem: Brand / Chain / Location",
  "exp.saaf_layer_desc.3": "Configurable flow per client · Admin always has final veto",
  "exp.saaf_layer_desc.4": "Push · WhatsApp · Email by role",
  "exp.saaf_layer_desc.5": "Real results feed back into each agent in the next cycle",
  "exp.saaf_layer_desc.6": "Builds the payload and publishes via API · Anomaly monitor",
  "exp.saaf_layer_desc.7": "Gamification engine · Waiter apps · API endpoints",
  "exp.saaf_layer_title.0": "Data sources",
  "exp.saaf_layer_title.1": "Normalized connectors",
  "exp.saaf_layer_title.2": "Proposing agents",
  "exp.saaf_layer_title.3": "Approval engine",
  "exp.saaf_layer_title.4": "Notification channel",
  "exp.saaf_layer_title.5": "Learning engine",
  "exp.saaf_layer_title.6": "Publishing agent",
  "exp.saaf_layer_title.7": "Superlikers Platform",
  "exp.saaf_llm_label.0": "Primary LLM",
  "exp.saaf_llm_sub.0": "Complex reasoning · 200K tokens · excellent Spanish",
  "exp.saaf_llm_val.0": "Claude Sonnet",
  "exp.saaf_notif_label.0": "Notifications",
  "exp.saaf_notif_sub.0": "Push iOS/Android · Inline approval buttons",
  "exp.saaf_notif_val.0": "WhatsApp Business + FCM",
  "exp.safe0_td0.0": "Instrument",
  "exp.safe0_td0.1": "SAFE (Y Combinator standard)",
  "exp.safe0_td1.0": "Valuation Cap",
  "exp.safe0_td1.1": "USD $6,000,000",
  "exp.safe0_td2.0": "Discount",
  "exp.safe0_td2.1": "20% on future round",
  "exp.safe0_td3.0": "Minimum ticket",
  "exp.safe0_td3.1": "USD $25,000",
  "exp.safe0_td4.0": "In-kind contribution",
  "exp.safe0_td4.1": "Welcome for Advisory Board",
  "exp.safe1_td0.0": "Instrument",
  "exp.safe1_td0.1": "SAFE (Y Combinator standard)",
  "exp.safe1_td1.0": "Valuation Cap",
  "exp.safe1_td1.1": "USD $8,000,000",
  "exp.safe1_td2.0": "Discount",
  "exp.safe1_td2.1": "15% on future round",
  "exp.safe1_td3.0": "Minimum ticket",
  "exp.safe1_td3.1": "USD $50,000",
  "exp.safe1_td4.0": "In-kind contribution",
  "exp.safe1_td4.1": "Case by case",
  "exp.stat_label.0": "Restaurants worldwide",
  "exp.stat_label.1": "Active waiters globally",
  "exp.stat_label.2": "Global investment in waiter motivation",
  "exp.stat_note.0": "Total addressable market",
  "exp.stat_note.1": "The most underutilized salesforce in the industry",
  "exp.stat_note.2": "No standard exists today. That is the opportunity.",
  "exp.t1_chip.0": "Deep industry knowledge",
  "exp.t1_chip.1": "Global network of restaurants and chains",
  "exp.t1_chip.2": "Participation via SAFE (in-kind contribution)",
  "exp.t1_chip.3": "Co-hosts of the International Gala",
  "exp.t1_chip.4": "Voice in product and pricing decisions",
  "exp.t1_chip.5": "20% commissions → applied to the SAFE",
  "exp.t2_chip.0": "Mexico · Grupo Restaurantero CDMX",
  "exp.t2_chip.1": "Brazil · São Paulo, Rio de Janeiro",
  "exp.t2_chip.2": "Spain · Madrid, Barcelona, Seville",
  "exp.t2_chip.3": "USA · Miami, Los Angeles, New York",
  "exp.t2_chip.4": "Panama · Central America",
  "exp.t2_chip.5": "+50 planned territories",
  "exp.t3_chip.0": "HOT POS (Colombia · active)",
  "exp.t3_chip.1": "Toast (USA)",
  "exp.t3_chip.2": "Square (USA/UK)",
  "exp.t3_chip.3": "Lightspeed (Global)",
  "exp.t3_chip.4": "Bind ERP (Mexico)",
  "exp.t3_chip.5": "Totvs (Brazil)",
  "exp.t3_chip.6": "Micros Oracle (Global)",
  "exp.t3_chip.7": "Clover (USA)",
  "exp.t3_chip.8": "+40 on roadmap",
  "exp.t4_chip.0": "Coca-Cola (Colombia · active conversations)",
  "exp.t4_chip.1": "AB InBev / Bavaria (Superlikers client)",
  "exp.t4_chip.2": "Pernod Ricard (Superlikers client)",
  "exp.t4_chip.3": "OXXO (parallel pilot · 28,000 stores)",
  "exp.t4_chip.4": "Essity",
  "exp.t4_chip.5": "Diageo",
  "exp.t4_chip.6": "Heineken",
  "exp.t4_chip.7": "Nestlé Food Service",
  "exp.t5_chip.0": "ACODRES (Colombia · in conversation)",
  "exp.t5_chip.1": "CANIRAC (Mexico)",
  "exp.t5_chip.2": "NRA (National Restaurant Association · USA)",
  "exp.t5_chip.3": "FEHR (Spain)",
  "exp.t5_chip.4": "ABRASEL (Brazil)",
  "exp.t5_chip.5": "Eurotoques (Europe)",
  "exp.t6_chip.0": "Service consultants and coaches",
  "exp.t6_chip.1": "Chefs with digital audiences",
  "exp.t6_chip.2": "Restaurant owners with social media presence",
  "exp.t6_chip.3": "Hospitality academy trainers",
  "exp.t6_chip.4": "Culinary content creators",
  "exp.t7_chip.0": "SENA (Colombia)",
  "exp.t7_chip.1": "Hospitality schools · Spain",
  "exp.t7_chip.2": "Johnson &amp; Wales (USA)",
  "exp.t7_chip.3": "ICESI / UNINORTE (Colombia)",
  "exp.t7_chip.4": "Regional culinary academies",
  "exp.tier_badge.0": "Layer 1 · Most strategic",
  "exp.tier_badge.1": "Layer 2",
  "exp.tier_badge.2": "Layer 3",
  "exp.tier_badge.3": "Layer 4",
  "exp.tier_badge.4": "Layer 5",
  "exp.tier_badge.5": "Layer 6",
  "exp.tier_badge.6": "Layer 7",
  "exp.timeline_target.0": "<span class=\"highlight\">10,000</span> restaurants",
  "exp.timeline_target.1": "<span class=\"highlight\">100,000</span> restaurants",
  "exp.timeline_target.2": "<span class=\"highlight\">1,000,000</span> restaurants",
  "exp.tl_2026.0": "SAAF in full production (HOT + Coca-Cola)",
  "exp.tl_2026.1": "Self-service funnel 100% operational",
  "exp.tl_2026.2": "First 10 authorized partners active",
  "exp.tl_2026.3": "App in Latin American Spanish (MX, CO, PE variants)",
  "exp.tl_2026.4": "In-app gamified LMS",
  "exp.tl_2026.5": "First National Master Waiters Gala",
  "exp.tl_2029.0": "App in English (EN-US) and Portuguese (PT-BR)",
  "exp.tl_2029.1": "Network of 50 certified active partners",
  "exp.tl_2029.2": "20+ POS connectors (Toast, Square, Lightspeed…)",
  "exp.tl_2029.3": "AI Course Generator in production",
  "exp.tl_2029.4": "Public API Marketplace for integrators",
  "exp.tl_2029.5": "First International Master Waiters Gala",
  "exp.tl_2031.0": "10+ languages and 20+ cultural variants",
  "exp.tl_2031.1": "500+ authorized partners in 60+ countries",
  "exp.tl_2031.2": "SAAF 100% autonomous, with no scaling friction",
  "exp.tl_2031.3": "50+ global POS connectors integrated",
  "exp.tl_2031.4": "PLG as the primary acquisition engine",
  "exp.tl_2031.5": "Master Waiters Gala across 3 continents",
  "tech.badge.001": "Server role name (waiter/garçon/garzone)",
  "tech.badge.002": "Local currency and number format",
  "tech.badge.003": "Localized rewards catalog",
  "tech.badge.004": "Sales metrics by business type",
  "tech.badge.005": "Role terminology",
  "tech.badge.006": "Communication tone",
  "tech.badge.007": "Peak engagement hours by time zone",
  "tech.badge.008": "Representative imagery and avatars",
  "tech.badge.009": "In-app guides translated by Claude",
  "tech.badge.010": "24/7 multi-language support chatbot",
  "tech.badge.011": "WhatsApp onboarding for markets without reliable email",
  "tech.badge.012": "Video tutorials (auto-dubbed via ElevenLabs)",
  "tech.badge.013": "Adaptive contextual tooltips",
  "tech.badge.014": "Direct Sponsor",
  "tech.kpi_val.1": "60 months",
  "tech.li.001": "React Native + Expo — one codebase for iOS and Android",
  "tech.li.002": "i18next — translation management with per-module namespaces",
  "tech.li.003": "LaunchDarkly — feature flags for market variants",
  "tech.li.004": "Contentful CMS — dynamic content without redeploy",
  "tech.li.005": "Claude API — translation generation and validation",
  "tech.li.006": "Lokalise — string management platform",
  "tech.li.007": "<strong>Super Meseros</strong> — ES-CO, neutral masculine tone",
  "tech.li.008": "<strong>Maestras de la Mesa</strong> — ES-CO, feminine (Crepes &amp; Waffles)",
  "tech.li.009": "Corporate white-label — for chains with their own brand",
  "tech.li.010": "Claude API — content generation by market",
  "tech.li.011": "Vercel Analytics / PostHog — A/B testing and funnels",
  "tech.li.012": "Ahrefs / Semrush — local SEO strategy by country",
  "tech.li.013": "masterwaitersglobal.com/[locale]/restaurants → owners",
  "tech.li.014": "masterwaitersglobal.com/gala → annual global event",
  "tech.li.015": "Viral waiter challenge (#MasterWaitersChallenge)",
  "tech.li.016": "Waiter success story (30–60 sec)",
  "tech.li.017": "Behind the scenes of a Gala",
  "tech.li.018": "Service micro-lesson",
  "tech.li.019": "Duet with a restaurateur",
  "tech.li.020": "Gamification ROI (real data)",
  "tech.li.021": "Chain case study (HOT, OXXO)",
  "tech.li.022": "Full tutorial for admins",
  "tech.li.023": "Series: \"The Art of Service\"",
  "tech.li.024": "Claude generates a 30-day calendar per account",
  "tech.li.025": "Canva API for automated design",
  "tech.li.026": "ElevenLabs for multi-language dubbing",
  "tech.li.027": "Captions.ai for automatic subtitles",
  "tech.li.028": "Buffer/Metricool for scheduled publishing",
  "tech.li.029": "<strong>PLG:</strong> 30-day free trial → in-app conversion",
  "tech.li.030": "<strong>Referrals:</strong> 1 restaurant brings another → 1 month free",
  "tech.li.031": "<strong>POS partners:</strong> HOT POS recommends MW to its clients",
  "tech.li.032": "<strong>Brands:</strong> Coca-Cola promotes to its 5,000 restaurants",
  "tech.li.033": "<strong>Delivery platforms:</strong> Rappi, UberEats as a channel",
  "tech.li.034": "Claude chatbot on the web (pre-qualifies leads)",
  "tech.li.035": "Interactive demo with realistic mock data",
  "tech.li.036": "Real-time ROI calculator",
  "tech.li.037": "Auto-generated commercial proposal (signable PDF)",
  "tech.li.038": "Personalized onboarding video by segment",
  "tech.li.039": "Health score per restaurant (usage, engagement, results)",
  "tech.li.040": "Early churn alerts → automatic intervention",
  "tech.li.041": "Claude 24/7 multi-language support chatbot",
  "tech.li.042": "Automated in-app NPS + response analysis",
  "tech.li.043": "Human escalation only when the score requires it",
  "tech.li.044": "<strong>Step 1 (5 min):</strong> Registration + business details",
  "tech.li.045": "<strong>Step 2 (10 min):</strong> Assistant connects POS or loads menu",
  "tech.li.046": "<strong>Step 3 (5 min):</strong> Invite waiters (unique link per location)",
  "tech.li.047": "<strong>Step 4 (auto):</strong> SAAF generates the first challenge slate",
  "tech.li.048": "<strong>Step 5 (5 min):</strong> Admin approves with one click",
  "tech.li.049": "<strong>Goal:</strong> first active challenge in &lt; 48 hours",
  "tech.li.050": "<strong>Step 1 (2 min):</strong> Scan restaurant QR code",
  "tech.li.051": "<strong>Step 3 (auto):</strong> Receives welcome challenge",
  "tech.li.052": "<strong>Step 4 (shift):</strong> Complete challenge → earn first Super Moneda",
  "tech.li.053": "<strong>Goal:</strong> first coin earned before the end of the first shift",
  "tech.li.054": "Onboarding is the first challenge of the game",
  "tech.li.055": "Agent prompts in 10+ languages (Claude multi-language)",
  "tech.li.056": "Culturally adapted challenge templates per market",
  "tech.li.057": "Support for 20+ currencies (COP, USD, EUR, MXN, BRL…)",
  "tech.li.058": "Rewards catalog localized by country",
  "tech.li.059": "POS connector library (currently 2, target: 50+)",
  "tech.li.060": "Public SAAF API for integration partners",
  "tech.li.061": "White-label SAAF for regional partners",
  "tech.li.062": "<strong>No POS:</strong> manual entry / Google Sheets connector",
  "tech.li.063": "Brand product courses (sponsored)",
  "tech.li.064": "Service techniques by restaurant type",
  "tech.li.065": "Certifications with a profile badge",
  "tech.li.066": "AI Course Generator: brand provides specs, AI generates the course",
  "tech.li.067": "3–5 min micro-lessons (mobile-first)",
  "tech.li.068": "Free versions of popular courses",
  "tech.li.069": "Series \"Secrets of Perfect Service\"",
  "tech.li.070": "Platform tutorials for admins",
  "tech.li.071": "Successful waiter stories (UGC)",
  "tech.li.072": "SEO as an organic acquisition channel",
  "tech.li.073": "Claude API → generates course script",
  "tech.li.074": "ElevenLabs → multi-language narration",
  "tech.li.075": "Synthesia or HeyGen → video with avatar",
  "tech.li.076": "Lokalise → LMS UI strings",
  "tech.li.077": "Legal documentation per country ($100K+)",
  "tech.li.078": "12–18 months to launch",
  "tech.li.079": "Franchisee can alter the product",
  "tech.li.080": "Difficult to control quality",
  "tech.li.081": "Not natural for SaaS",
  "tech.li.082": "Setup in 60 days per market",
  "tech.li.083": "30% of portfolio MRR",
  "tech.li.084": "Master Waiters retains IP and product",
  "tech.li.085": "Territorial exclusivity with minimums",
  "tech.li.086": "Maximum quality control",
  "tech.li.087": "Requires hiring a local team",
  "tech.li.088": "Impossible for 1M restaurants",
  "tech.li.089": "Only viable in anchor markets",
  "tech.li.090": "16-hour online course (multi-language)",
  "tech.li.091": "Certification exam with minimum score",
  "tech.li.092": "Sandbox: demo restaurant with realistic mock data",
  "tech.li.093": "Sales playbook localizable per market",
  "tech.li.094": "HubSpot CRM for account tracking",
  "tech.li.095": "Real-time commissions dashboard",
  "tech.li.096": "Sales materials library (Sanity CMS)",
  "tech.li.097": "Dedicated WhatsApp Business support",
  "tech.li.098": "Partner leaderboard (the same game for them)",
  "tech.li.099": "Public documentation (Readme.io)",
  "tech.li.100": "SDK for POS providers",
  "tech.li.101": "Webhook library for game events",
  "tech.li.102": "Sandbox for integration testing",
  "tech.li.103": "POS integrator certification",
  "tech.li.104": "Event website (landing + registration)",
  "tech.li.105": "Global livestream with subtitles",
  "tech.li.106": "Awards program: \"Best waiters of the year\"",
  "tech.li.107": "Post-event content on YouTube/LinkedIn",
  "tech.li.108": "Nominations from within the app",
  "tech.li.109": "LADCC's LinkedIn as editorial channel",
  "tech.li.110": "Podcast \"The Art of Service\"",
  "tech.li.111": "Monthly webinars for restaurateurs",
  "tech.li.112": "SAAF MVP in production (HOT + Coca-Cola)",
  "tech.li.113": "First cohort of 10 partners",
  "tech.li.114": "App in ES-CO + ES-MX",
  "tech.li.115": "App in EN-US + PT-BR + ES variants",
  "tech.li.116": "30 certified active partners",
  "tech.li.117": "SAAF with 10+ POS connectors",
  "tech.li.118": "AI Course Generator in production",
  "tech.li.119": "App in FR + IT + DE",
  "tech.li.120": "100 partners in 30+ countries",
  "tech.li.121": "SAAF with 25+ POS connectors",
  "tech.li.122": "White-label for own chains",
  "tech.li.123": "10+ languages in production",
  "tech.li.124": "250 partners in 50+ countries",
  "tech.li.125": "SAAF with 40+ POS connectors",
  "tech.li.126": "Partner Agent active",
  "tech.li.127": "Gala across 2 continents",
  "tech.li.128": "15+ languages in production",
  "tech.li.129": "500+ partners in 60+ countries",
  "tech.li.130": "SAAF fully autonomous",
  "tech.li.131": "Integration with 50+ POS",
  "tech.li.132": "Global industry standard",
  "tech.li.133": "Global Gala across 3 continents",
  "tech.li.134": "Next.js 14 (App Router) — native i18n routing",
  "tech.li.135": "Sanity CMS — flexible, API-first, multi-language",
  "tech.li.136": "Vercel — hosting + Edge Network + Analytics",
  "tech.li.137": "masterwaitersglobal.com/[locale]/brands → sponsors",
  "tech.li.138": "masterwaitersglobal.com/[locale]/waiters → download app",
  "tech.li.139": "masterwaitersglobal.com/[locale]/partners → partners",
  "tech.li.140": "masterwaitersglobal.com/[locale]/investors → data room",
  "tech.li.141": "Investor/partner updates",
  "tech.li.142": "Lottie → gamified animations",
  "tech.li.143": "High regulatory complexity",
  "tech.li.144": "Light setup fee ($5K–$15K)",
  "tech.li.145": "Partner handles sales, CS, and local events",
  "tech.li.146": "Very high operational cost",
  "tech.li.147": "Colombia, Mexico, USA: yes. Rest: no",
  "tech.li.148": "Co-branded marketing templates (Canva API)",
  "tech.li.149": "Partner portal: CRM + pipeline + commissions",
  "tech.li.150": "Demo environment (restaurant sandbox)",
  "tech.li.151": "\"State of Waiter Gamification\" — annual report",
  "tech.li.152": "Awards program: UGC + PR engine",
  "tech.li.153": "Full self-service funnel",
  "tech.li.154": "Basic in-app LMS",
  "tech.li.155": "First National Gala",
  "tech.li.156": "Public API Marketplace",
  "tech.li.157": "First International Gala",
  "tech.li.158": "Second International Gala",
  "tech.li.159": "Consolidated thought leadership",
  "tech.li.160": "PLG as the primary engine",
  "tech.li.161": "<strong>Master Waiters</strong> — EN-US / EN-GB",
  "tech.li.162": "<strong>Master Waiters</strong> — PT-BR (Brazil)",
  "tech.li.163": "<strong>Master Waiters</strong> — ES-MX, ES-AR, ES-PE",
  "tech.li.164": "<strong>Maîtres Masters</strong> — FR-FR (year 5)",
  "tech.li.165": "<strong>Associations:</strong> Acodres, Camacol, CANIRAC Mexico",
  "tech.li.166": "<strong>Inbound SEO:</strong> blog + YouTube as organic traffic",
  "tech.li.167": "<strong>Step 2 (3 min):</strong> Create profile (name, photo, shift)",
  "tech.li.168": "<strong>Colombia:</strong> HOT (ready), Toast, Siesa",
  "tech.li.169": "<strong>Mexico:</strong> Bind ERP, Micros, Lightspeed",
  "tech.li.170": "<strong>USA:</strong> Toast, Square, Clover, Aloha",
  "tech.li.171": "<strong>Brazil:</strong> Totvs, Stone",
  "tech.li.172": "<strong>Spain:</strong> Posi, Agora",
  "tech.ugc.2": "Waiters who share their achievements on social are the best marketing. The app includes a native \"Share victory\" feature that automatically generates a branded card with the achievement, the prize and the restaurant name.",
  "tech.ugc.4": "Sponsoring brands (Direct Sponsor) pay for courses featuring their products inside the LMS. A course like \"How to sell Coca-Cola Zero perfectly\" funded by Coca-Cola, which also reinforces the active gamification strategy of SAAF. The LMS is an additional revenue channel, not just a cost.",
  "tech.viral_loop.0": "Brand (Coca-Cola) pays to activate challenges in restaurants<br/>\n          → Restaurant sees +25% uplift in category sales<br/>\n          → Restaurant tells other restaurants<br/>\n          → Waiter shares their prize on social media<br/>\n          → Waiter takes the concept to a new job<br/>\n          → New restaurants ask for the platform<br/>\n<strong style=\"color:var(--color-text-primary);\">→ The brand finances the platform's growth</strong>"
,
  "hub.footer_contact.0": "Luis Alberto Del Castillo · Founder &amp; CEO<br/><a>[email protected]</a> · +57 305 745 4823",
  "saaf.footer_contact.0": "Luis Alberto Del Castillo Cadavid<br/>Founder &amp; CEO, Superlikers (2010)<br/><a>[email protected]</a><br/>+57 305 745 4823 · Bogotá, Colombia"
,
  "hub.section_label.2": "Financial models",
  "hub.card_type.4": "Private",
  "hub.card_title.4": "Financial Models<br/>Private Access",
  "hub.card_desc.4": "Complete financial model in Excel (15 sheets, 60 months, 3 scenarios) and interactive simulator with real-time sliders. Access restricted to invited investors.",
  "saaf.cover_title.0": "The engine that makes it possible<br><em>1 to 1,000,000</em>",
  "saaf.cover_sub.0": "Why the most ambitious gamification platform in the restaurant sector cannot scale without autonomous intelligence — and how SAAF solves exactly that problem.",
  "saaf.cover_meta_label.0": "Product",
  "saaf.cover_meta_label.1": "Platform",
  "saaf.cover_meta_label.2": "Active pilot",
  "saaf.cover_meta_val.2": "23 HOT branches · Colombia",
  "saaf.cover_meta_label.3": "5-year goal",
  "saaf.cover_meta_val.3": "1,000,000 restaurants globally",
  "saaf.thesis_label.0": "The problem thesis",
  "saaf.thesis_text.0": "Every challenge a waiter sees on their app was designed by a human Engagement Manager. At 23 restaurants, that's manageable. At 5,000 — the condition Coca-Cola Colombia puts on the table — that model would require a team proportional to the client count. With that model, the company doesn't scale. Growth destroys the margin.",
  "saaf.stat_label.0": "Restaurants worldwide",
  "saaf.stat_note.0": "Total addressable market",
  "saaf.stat_label.1": "Waiters active globally",
  "saaf.stat_note.1": "The most underutilized salesforce on the planet",
  "saaf.stat_label.2": "Global investment in waiter motivation",
  "saaf.stat_note.2": "No standard exists today. That is the opportunity.",
  "saaf.ba_header_before.0": "Without SAAF — linear growth",
  "saaf.ba_item_before.0": "Every new client requires proportional team time",
  "saaf.ba_item_before.1": "Manual design of every challenge for every restaurant",
  "saaf.ba_item_before.2": "More clients = more people = more operational cost",
  "saaf.ba_item_before.3": "Impossible to scale to 5,000 without destroying the margin",
  "saaf.ba_item_before.4": "Configuration errors detected by a human, late",
  "saaf.ba_header_after.0": "With SAAF — exponential growth",
  "saaf.ba_item_after.0": "The agent generates the monthly grid autonomously",
  "saaf.ba_item_after.1": "One EM can supervise 10× more clients with the same quality",
  "saaf.ba_item_after.2": "More restaurants = more data = better agent = better results",
  "saaf.ba_item_after.3": "5,000 restaurants with the same team serving 23 today",
  "saaf.ba_item_after.4": "Automatic monitor detects and corrects anomalies in real time",
  "saaf.three_components.0": "The three core components of the system:",
  "saaf.card_eyebrow.0": "Component 1",
  "saaf.card_eyebrow.1": "Component 2",
  "saaf.card_eyebrow.2": "Component 3",
  "saaf.card_eyebrow.3": "Learning engine",
  "saaf.card_body.0": "Analyzes 12+ months of POS history, the season, the brand portfolio and the month's objectives. Generates a complete grid — minimum 10 challenges, 4 quests and 2 missions — without anyone asking. Proposes 2–3 alternatives per opportunity for the human to choose.",
  "saaf.card_body.1": "Manages the human review flow configurable per client. For restaurant challenges, the admin explicitly approves. For brand challenges, Coca-Cola approves first and the admin has 24h to veto. The admin always has the final word.",
  "saaf.card_body.2": "Takes the approved proposal, builds the complete payload and publishes it via the Superlikers platform endpoints already in production. Continuously monitors and automatically unpublishes if it detects technical anomalies.",
  "saaf.card_body.3": "Real results (completion rate, real vs projected uplift, acceptance rate) feed back to the agent before the next monthly grid. The Engagement Manager's judgment is also incorporated as an editorial signal. The more restaurants, the better the agent.",
  "saaf.level_label.brand": "Brand level",
  "saaf.level_label.chain": "Chain level",
  "saaf.level_label.venue": "Branch level (final veto always here)",
  "saaf.agent_chip.brand1": "Brand Agent — Coca-Cola Colombia",
  "saaf.agent_chip.brand2": "CPG Brand Agent — for each brand in OXXO",
  "saaf.agent_chip.chain1": "Chain Agent — HOT Restaurants",
  "saaf.agent_chip.chain2": "OXXO Agent — central operator",
  "saaf.agent_chip.venue1": "Branch Agent — Restaurant 1",
  "saaf.agent_chip.venue2": "Branch Agent — Restaurant 2",
  "saaf.agent_chip.venueN": "Branch Agent — Restaurant N",
  "saaf.agent_chip.parallel": "× 5,000 parallel instances",
  "saaf.connector.network": "proposes challenges for the entire network",
  "saaf.connector.branches": "proposes challenges for its branches",
  "saaf.flow_intro.0": "The approval flow for brand challenges:",
  "saaf.flow_step.0": "Agent",
  "saaf.flow_step.0b": "Generates proposal",
  "saaf.flow_step.0c": "Proactive",
  "saaf.flow_step.1": "Reviews the grid",
  "saaf.flow_step.2": "Approves first",
  "saaf.flow_step.3": "Branch Admin",
  "saaf.flow_step.3b": "Final veto (24h)",
  "saaf.flow_step.3c": "Silence = publishes",
  "saaf.flow_step.4": "Platform",
  "saaf.flow_step.4b": "Live challenge for waiters",
  "saaf.badge_built.0": "Already in production ✓",
  "saaf.card_eyebrow.4": "Advantage 1 · Data flywheel",
  "saaf.card_eyebrow.5": "Advantage 2 · Deep integration",
  "saaf.card_eyebrow.6": "Advantage 3 · Autonomy with control",
  "saaf.card_eyebrow.7": "Advantage 4 · Generic architecture",
  "saaf.card_body.4": "Each published challenge generates learning signals. With 1M restaurants, SAAF has access to behavioral patterns from 50M waiters globally. No competitor can replicate that database without years of operation.",
  "saaf.card_body.5": "The real-time connection to HOT's POS already operates in production. Replicating that integration across 50+ global POS systems requires years of technical work and commercial agreements that Master Waiters is already building.",
  "saaf.card_body.6": "The branch administrator's veto is not a concession — it is the differentiator that HOT Restaurants demands to scale. Competitors that offer automation without control will lose the biggest operators.",
  "saaf.card_body.7": "SAAF is not hardcoded for restaurants. The same architecture serves OXXO Engage (28K stores), corporate clients and any gamified ecosystem. Each new client strengthens the system for everyone else.",
  "saaf.card_eyebrow.llm": "Primary LLM",
  "saaf.card_eyebrow.infra": "Infrastructure",
  "saaf.card_body.8": "200K context tokens — enough to pass 12+ months of POS data + instructions in a single call. Excellent Spanish. Consistent structured reasoning for budget optimization.",
  "saaf.card_body.9": "Step Functions for the per-client configurable approval flow. Lambda + Batch for parallel generation at scale. SQS to decouple generation from processing. RDS PostgreSQL for state and configuration.",
  "saaf.mvp_left_eyebrow.0": "Non-negotiable MVP components",
  "saaf.mvp_right_eyebrow.0": "What the MVP proves to Coca-Cola",
  "hub.header_title.0": "The Operating System for the World's Restaurant Salesforce",
  "hub.deck_url.0": "https://docs.google.com/presentation/d/e/2PACX-1vQ-nZBLy4exr1ULkNjvcJ2ZYvRsU3D001Zjv6Pi5kbxo2VScGXLSBdZrQjgZIf9TA/pub?start=false&loop=false&delayms=3000",
  "hub.xg_pill.0": "Vertical 01 of XGAIGE",
  "hub.xgb_eyebrow.0": "Master Waiters is chapter one",
  "hub.xgb_title.0": "There are more chapters being written.",
  "hub.xgb_body.0": "Master Waiters is the first vertical of XGAIGE — a company-builder for gamified ecosystems. Pharma Champions and Super Asesoras are the next chapters of the same thesis.",
  "hub.xgb_cta.0": "Discover XGAIGE",
  "saaf.tl_sublabel.year1": "Year 1",
  "saaf.tl_sublabel.year2_a": "Year 2",
  "saaf.tl_sublabel.year2_b": "Year 2",
  "saaf.tl_sublabel.year3": "Year 3",
  "saaf.tl_sublabel.year4": "Year 4",
  "saaf.tl_sublabel.year5": "Year 5",
  "saaf.scale_bar.0": "23 → 10K",
  "saaf.scale_bar.1": "50K restaurants",
  "saaf.scale_bar.2": "200K restaurants",
  "saaf.scale_bar.3": "500K restaurants",
  "saaf.scale_bar.4": "1,000,000 restaurants",
  "saaf.scale_note.0": "◆ SAAF MVP live",
  "saaf.scale_note.1": "◆ SAAF learns from 200K challenges/month",
  "saaf.scale_note.2": "◆ PLG + 500 partners + global brands",
  "saaf.scale_footnote.0": "* Average ACV of USD $200/month per restaurant (SaaS + Super Monedas). 1M restaurants = ~7% of the global market.",
  "saaf.tl_sublabel.13weeks": "13 weeks",
  "saaf.tl_target.0": "SAAF MVP in production",
  "saaf.tl_sub.0": "Colombia · HOT Restaurants · 23 branches",
  "saaf.tl_li.0": "Proposing Agent generating batch grid",
  "saaf.tl_li.1": "Approval Engine Flow A and B live",
  "saaf.tl_li.2": "Publishing Agent integrated with platform",
  "saaf.tl_li.3": "Approval interface for admin and Coca-Cola",
  "saaf.tl_li.4": "Inference cost: ~$12–20 USD/month (23 branches)",
  "saaf.tl_li.5": "Team: 4 full-time engineers",
  "saaf.tl_sublabel.q4": "Q4",
  "saaf.tl_target.1": "Validation with Coca-Cola Colombia",
  "saaf.tl_sub.1": "Argument for the 5,000 restaurants",
  "saaf.tl_li.6": "Autonomous grid operating in 23 branches",
  "saaf.tl_li.7": "EM approval rate ≥ 70% without editing",
  "saaf.tl_li.8": "Anomaly monitor and learning engine",
  "saaf.tl_li.9": "Pipeline Mexico + Peru open",
  "saaf.tl_target.2": "Scale to full Coca-Cola + OXXO",
  "saaf.tl_sub.2": "Colombia · Mexico · Peru · OXXO 28K stores",
  "saaf.tl_li.10": "SAAF in parallel for multiple ecosystems",
  "saaf.tl_li.11": "Agent learns from millions of completed challenges",
  "saaf.tl_li.12": "50+ certified POS connectors",
  "saaf.tl_li.13": "Inference cost: ~$2,500–4,000 USD/month (5K restaurants)",
  "saaf.tl_year.2028plus": "Years 3–5",
  "saaf.tl_target.3": "SAAF as global competitive advantage",
  "saaf.tl_sub.3": "USA · Brazil · Spain · Europe · Asia Pacific",
  "saaf.tl_li.14": "500+ regional partners using SAAF as base",
  "saaf.tl_li.15": "Global brands (Heineken, Diageo, Nestlé) on SAAF",
  "saaf.tl_li.16": "PLG as primary acquisition engine",
  "saaf.tl_li.17": "1M restaurants without proportional team growth",
  "saaf.cost_th.0": "Scenario",
  "saaf.cost_th.1": "Restaurants",
  "saaf.cost_th.2": "Inference cost / month",
  "saaf.cost_th.3": "Projected ARR",
  "saaf.cost_th.4": "Cost/revenue ratio",
  "saaf.cost_row.0": "HOT pilot (today)",
  "saaf.cost_row.1": "Year 1 (10K restaurants)",
  "saaf.cost_row.2": "Year 5 (1M restaurants)",
  "saaf.cost_footnote.0": "* Inference cost scales linearly with restaurants but stays below 0.04% of ARR in all projected scenarios.",
  "saaf.mvp_left_content.0": "✓ Proposing Agent (monthly batch grid)<br>✓ Approval Engine (Flow A and Flow B)<br>✓ Publishing Agent (Superlikers integration)<br>✓ Restaurant qualitative signal channel<br>✓ Admin + Coca-Cola approval interface<br>✓ Push / WhatsApp / Email notification channel",
  "saaf.mvp_right_content.0": "→ The agent understands the context of each restaurant<br>→ The approval flow respects HOT's autonomy<br>→ 23 branches without operational team growth<br>→ The model scales to 5,000 without architectural changes<br>→ EM approval rate ≥ 70% without editing<br>→ Real vs baseline uplift measurable in &lt;3 months",
};

const KEY = 'mw-lang';
let lang = localStorage.getItem(KEY) || 'es';
const CACHE = {};  // Stores original ES innerHTML

function apply(l){
  lang = l;
  localStorage.setItem(KEY, l);
  document.querySelectorAll('[data-i18n]').forEach(function(el){
    var key = el.getAttribute('data-i18n');
    if(l === 'en'){
      if(CACHE[key] === undefined) CACHE[key] = el.innerHTML;
      if(T[key] !== undefined && T[key] !== '') el.innerHTML = T[key];
    } else {
      if(CACHE[key] !== undefined) el.innerHTML = CACHE[key];
    }
  });
  // Handle dynamic hrefs (e.g. deck links to ES vs EN Google Slides)
  document.querySelectorAll('[data-i18n-href]').forEach(function(el){
    var key = el.getAttribute('data-i18n-href');
    if(l === 'en'){
      if(CACHE['__href__' + key] === undefined) CACHE['__href__' + key] = el.getAttribute('href');
      if(T[key] !== undefined && T[key] !== '') el.setAttribute('href', T[key]);
    } else {
      if(CACHE['__href__' + key] !== undefined) el.setAttribute('href', CACHE['__href__' + key]);
    }
  });
  document.documentElement.lang = l;
  var f = document.querySelector('.card.featured');
  if(f) f.setAttribute('data-featured-label', l==='en' ? '★ Featured' : '★ Principal');
  updateBtn(l);
}

function updateBtn(l){
  var es = document.getElementById('mw-es');
  var en = document.getElementById('mw-en');
  if(!es||!en) return;
  var gold = 'var(--gold,#C9A447)';
  var dim  = 'rgba(180,170,150,0.45)';
  es.style.color = l==='es' ? gold : dim;
  es.style.fontWeight = l==='es' ? '600' : '400';
  en.style.color = l==='en' ? gold : dim;
  en.style.fontWeight = l==='en' ? '600' : '400';
}

function inject(){
  var btn = document.createElement('div');
  btn.id = 'mw-lang-toggle';
  btn.innerHTML =
    '<span id="mw-es">ES</span>' +
    '<span style="margin:0 3px;opacity:0.2;color:var(--gold,#C9A447)">|</span>' +
    '<span id="mw-en">EN</span>';
  btn.style.cssText = [
    'position:fixed','top:18px','right:18px','z-index:9999',
    'display:flex','align-items:center','gap:2px',
    'background:rgba(10,8,6,0.85)',
    'border:0.5px solid rgba(201,164,71,0.38)',
    'border-radius:100px','padding:6px 14px',
    'font-size:11px','letter-spacing:0.12em',
    'font-family:Outfit,DM Sans,sans-serif',
    'cursor:pointer',
    'backdrop-filter:blur(10px)',
    '-webkit-backdrop-filter:blur(10px)',
    'user-select:none','transition:border-color 0.2s'
  ].join(';');
  btn.addEventListener('mouseenter',function(){btn.style.borderColor='rgba(201,164,71,0.72)';});
  btn.addEventListener('mouseleave',function(){btn.style.borderColor='rgba(201,164,71,0.38)';});
  btn.addEventListener('click',function(){apply(lang==='es'?'en':'es');});
  document.body.appendChild(btn);
  updateBtn(lang);
}

document.addEventListener('DOMContentLoaded',function(){
  inject();
  var style = document.createElement('style');
  style.textContent = '.card.featured::after{content:attr(data-featured-label)!important}';
  document.head.appendChild(style);
  if(lang !== 'es'){
    apply(lang);
  } else {
    updateBtn('es');
  }
});

// Expose apply() so external components (e.g. mw-header.js) can trigger language changes
window.mwApplyLang = apply;

})();
